### ISSUE TITLE
Fields with None causing 'copy down' effect in tool Output

### ISSUE THREAD

**Issue by daqieq** [alteryx/snakeplane#28]
I wanted my custom snakeplane tool to output `[Null]` in Alteryx Designer, so I changed all `np.NaN` in the output dataframe to `None` (the dataframe is from the end of the `def process_data()`:
![image](https://user-images.githubusercontent.com/40532020/67133173-893cf880-f1c0-11e9-83d6-8032c5d25919.png)

However, this is causing the last non-None value to be copied 'down' the column in the output from the tool:
![image](https://user-images.githubusercontent.com/40532020/67133216-b9849700-f1c0-11e9-944a-373b7f355fd0.png)

I tried tracing this through the snakeplane classes, but lost track after the `push_records()` function in helper_classes.py.  My only theory was that `field.set_null()` wasn't overriding the previous value correctly. Could I be doing something wrong?

**Comment by daqieq** [comment]
Note - The version.py file has `__version__ = "1.0.0-alpha9"`. Would it help resolve this issue to upgrade to alpha13?

**Comment by dme722** [comment]
Hey @daqieq! We haven't looked into this one quite yet, but will hopefully have an answer for you soon!

**Comment by daqieq** [comment]
Update - Upgrading to snakeplane==1.0.0a20 resolved this issue for me.
